# Generated by Django 4.2.7 on 2023-12-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("score", models.FloatField(blank=True, default="", null=True)),
                (
                    "quantity_review",
                    models.IntegerField(blank=True, default="", null=True),
                ),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
