# Generated by Django 4.2.7 on 2023-12-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_food_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="unit",
            field=models.CharField(default="บาทต่อถุง", max_length=100),
        ),
    ]
