# Generated by Django 4.2.7 on 2023-12-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_food_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
