# Generated by Django 4.2.7 on 2023-12-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_food_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="quantity_review",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
