# Generated by Django 4.2.7 on 2023-12-02 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_food_quantity_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historysale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2023, 12, 2, 16, 16, 20, 861986)
                    ),
                ),
                ("food", models.ManyToManyField(related_name="food", to="app.food")),
            ],
        ),
    ]
