# Generated by Django 4.2.7 on 2023-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_historysale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historysale",
            name="date",
            field=models.DateField(),
        ),
    ]
