# Generated by Django 4.2.7 on 2023-12-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_historysale_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historysale",
            old_name="date",
            new_name="date_field",
        ),
        migrations.RemoveField(
            model_name="historysale",
            name="food",
        ),
        migrations.AddField(
            model_name="historysale",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.food",
            ),
        ),
    ]
