# Generated by Django 4.2.7 on 2023-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_date_historysale_date_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="status",
        ),
        migrations.AddField(
            model_name="food",
            name="options",
            field=models.CharField(
                choices=[
                    ("notchoose", "ไม่ได้เลือก"),
                    ("onsale", "วางขาย"),
                    ("soldout", "ขายหมดแล้ว"),
                ],
                default="notchoose",
                max_length=20,
            ),
        ),
    ]
