# Generated by Django 4.2.7 on 2023-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_food_status_food_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historysale",
            name="date_field",
            field=models.CharField(max_length=100),
        ),
    ]
