# Generated by Django 4.2.7 on 2023-12-04 04:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_historysale_date_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/image/",
             
            ),
        ),
    ]
