# Generated by Django 4.2.7 on 2023-12-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_food_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historysale",
            name="date_field",
            field=models.DateField(),
        ),
    ]
