# Generated by Django 4.2.7 on 2023-12-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0013_alter_historysale_date_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("11-20", "11-20 ปี"),
                            ("21-30", "21-30 ปี"),
                            ("31-40", "31-40 ปี"),
                            ("41-50", "41-50 ปี"),
                            ("51-60", "51-60 ปี"),
                            ("60+", "60 ปีขึ้น"),
                        ],
                        default="11-20",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "ผู้ชาบ"),
                            ("Female", "ผู้หญิง"),
                            ("Other", "อื่นๆ"),
                        ],
                        default="11-20",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
