# Generated by Django 4.2.7 on 2023-12-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_member_email_member_name_member_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                choices=[("Male", "ผู้ชาย"), ("Female", "ผู้หญิง"), ("Other", "อื่นๆ")],
                default="11-20",
                max_length=20,
            ),
        ),
    ]
