# Generated by Django 4.2.8 on 2023-12-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_member_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviewfood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField(max_length=300)),
                (
                    "score",
                    models.CharField(
                        choices=[
                            ("1", "1 ดาว"),
                            ("2", "2 ดาว"),
                            ("3", "3 ดาว"),
                            ("4", "4 ดาว"),
                            ("5", "5 ดาว"),
                        ],
                        default="5",
                        max_length=20,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.food"
                    ),
                ),
            ],
        ),
    ]
