# Generated by Django 4.2.8 on 2023-12-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_reviewfood"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewfood",
            old_name="score",
            new_name="rating",
        ),
    ]
