# Generated by Django 4.2.8 on 2023-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_reviewfood_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewfood",
            name="review",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
