# Generated by Django 4.2.7 on 2023-12-13 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_reviewfood_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewfood",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
