# Generated by Django 4.2.7 on 2023-12-13 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_reviewfood_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewfood",
            name="owner",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.member"
            ),
        ),
    ]
