# Generated by Django 4.2.7 on 2023-12-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_reviewfood_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewfood",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 ดาว"),
                    (2, "2 ดาว"),
                    (3, "3 ดาว"),
                    (4, "4 ดาว"),
                    (5, "5 ดาว"),
                ],
                default=5,
            ),
        ),
    ]
