# Generated by Django 4.2.7 on 2023-12-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_reviewfood_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
          
            ],
        ),
    ]
