# Generated by Django 4.2.7 on 2023-12-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
