# Generated by Django 4.2.7 on 2023-12-20 09:02

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_delete_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    mapbox_location_field.models.LocationField(
                        map_attrs={
                            "center": (15.268875, 104.8260654),
                            "style": "mapbox://styles/mapbox/streets-v11",
                            "zoom": 12,
                        }
                    ),
                ),
            ],
        ),
    ]
