# Generated by Django 4.2.7 on 2023-12-20 09:07

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="location",
            field=mapbox_location_field.models.LocationField(map_attrs={}),
        ),
    ]
