# Generated by Django 4.2.7 on 2023-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_rename_name_member_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewfood",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
