# Generated by Django 4.2.7 on 2023-12-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_alter_reviewfood_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewfood",
            name="review",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
