# Generated by Django 4.2.7 on 2024-01-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_alter_historysale_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="options",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Fooditem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "options",
                    models.CharField(
                        choices=[
                            ("notchoose", "ไม่ได้เลือก"),
                            ("onsale", "วางขาย"),
                            ("soldout", "ขายหมดแล้ว"),
                        ],
                        default="notchoose",
                        max_length=20,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.food"
                    ),
                ),
            ],
        ),
    ]
