# Generated by Django 4.2.7 on 2024-01-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_historysale_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="options",
            field=models.CharField(
                choices=[
                    ("notchoose", "ไม่ได้เลือก"),
                    ("onsale", "วางขาย"),
                    ("soldout", "ขายหมดแล้ว"),
                ],
                default="notchoose",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historysale",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.food",
            ),
        ),
        migrations.DeleteModel(
            name="Fooditem",
        ),
    ]
