# Generated by Django 4.2.7 on 2024-01-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_food_options_alter_historysale_food_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historysale",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
