# Generated by Django 4.2.7 on 2024-01-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_historysale_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="quantity_sale",
            field=models.IntegerField(default=0),
        ),
    ]
