# Generated by Django 4.2.7 on 2024-02-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_order_orderitemtype2_orderitemtype1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitemtype1",
            old_name="product",
            new_name="food",
        ),
        migrations.RenameField(
            model_name="orderitemtype2",
            old_name="products",
            new_name="foods",
        ),
    ]
