# Generated by Django 4.2.7 on 2024-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_rename_product_orderitemtype1_food_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemtype2",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
