# Generated by Django 4.2.7 on 2024-02-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_alter_order_time_receive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="time_receive",
            field=models.CharField(
                choices=[
                    ("10:00 AM", "10:00 น."),
                    ("10:30 AM", "10:30 น."),
                    ("11:00 AM", "11:00 น."),
                    ("11:30 AM", "11:30 น."),
                    ("12:00 PM", "12:00 น."),
                    ("12:30 PM", "12:30 น."),
                    ("01:00 PM", "13:00 น."),
                    ("01:30 PM", "13:30 น."),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
