# Generated by Django 4.2.7 on 2024-02-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_alter_order_time_receive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.IntegerField(default=0.0),
        ),
    ]
