# Generated by Django 4.2.7 on 2024-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_alter_transaction_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("expenses", "รายจ่าย"),
                    ("income", "รายรับ"),
                    ("leftover", "อาหารที่เหลือ"),
                ],
                max_length=10,
            ),
        ),
    ]
