# Generated by Django 4.2.7 on 2024-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_alter_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
