# Generated by Django 4.2.7 on 2024-02-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_transaction_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemtype1",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
