# Generated by Django 4.2.7 on 2024-02-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_alter_orderitemtype1_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
