# Generated by Django 4.2.7 on 2024-02-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="confirm",
            field=models.CharField(
                choices=[
                    ("wait_to_confirm", "รอยืนยัน"),
                    ("confirmed", "ยืนยันเเล้ว"),
                    ("received", "มารับเเล้ว"),
                    ("cancel", "ยกเลิก"),
                ],
                default="wait_to_confirm",
                max_length=20,
            ),
        ),
    ]
