# Generated by Django 4.2.7 on 2024-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_order_completed_alter_order_confirm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(null=True),
        ),
    ]
