# Generated by Django 4.2.7 on 2024-02-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_alter_order_cancel_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="line_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
