# Generated by Django 4.2.7 on 2024-02-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_member_line_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitemtype1",
            old_name="price",
            new_name="total_price",
        ),
        migrations.RenameField(
            model_name="orderitemtype2",
            old_name="price",
            new_name="total_price",
        ),
    ]
