# Generated by Django 4.2.7 on 2024-02-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_rename_total_price_orderitemtype2_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitemtype2",
            old_name="price",
            new_name="total_price",
        ),
    ]
