# Generated by Django 4.2.7 on 2024-02-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_rename_price_orderitemtype2_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemtype2",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
