# Generated by Django 4.2.7 on 2024-02-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_orderitemtype2_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemtype1",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitemtype2",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
