# Generated by Django 4.2.7 on 2024-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_remove_food_quantity_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="options",
        ),
        migrations.AddField(
            model_name="historysale",
            name="options",
            field=models.CharField(
                choices=[
                    ("notchoose", "ไม่ได้เลือก"),
                    ("onsale", "วางขาย"),
                    ("soldout", "ขายหมดแล้ว"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
