# Generated by Django 4.2.7 on 2024-03-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_remove_food_options_historysale_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historysale",
            name="options",
            field=models.CharField(
                choices=[
                    ("ไม่ได้เลือก", "ไม่ได้เลือก"),
                    ("วางขาย", "วางขาย"),
                    ("ขายหมดแล้ว", "ขายหมดแล้ว"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
