# Generated by Django 4.2.7 on 2024-03-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_food_quantity_sale"),
        ("app", "0075_alter_historysale_options"),
    ]

    operations = []
