# Generated by Django 4.2.7 on 2024-03-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_recommendus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app.member"
            ),
        ),
    ]
