# Generated by Django 4.2.7 on 2024-03-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0080_alter_member_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
