# Generated by Django 4.2.7 on 2024-03-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0082_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_receive",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
