# Generated by Django 4.2.7 on 2024-03-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_alter_order_cancel_reason_alter_order_time_receive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cancel_reason",
        ),
    ]
