# Generated by Django 4.2.7 on 2024-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0085_order_cancel_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                ("user_with", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TimeReceive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_receive", models.CharField(max_length=100)),
            ],
        ),
    ]
