# Generated by Django 4.2.7 on 2024-03-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0087_rename_user_with_cancelreason_use_with"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendus",
            name="user",
            field=models.ForeignKey(
                default="ไม่มีผู้ใช้งาน",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="app.member",
            ),
        ),
    ]
