# Generated by Django 4.2.7 on 2024-03-26 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0089_alter_recommendus_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendus",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.member",
            ),
        ),
    ]
