# Generated by Django 4.2.7 on 2024-04-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_alter_recommendus_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitemtype1",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitemtype2",
            name="user",
        ),
    ]
