# Generated by Django 4.2.7 on 2024-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0092_remove_orderitemtype1_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
