# Generated by Django 4.2.7 on 2024-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
