# Generated by Django 4.2.7 on 2024-01-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0005_remove_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
