# Generated by Django 4.2.7 on 2024-01-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0006_order_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="select",
            field=models.BooleanField(default=False),
        ),
    ]
