# Generated by Django 4.2.7 on 2024-01-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0007_product_select"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ManyToManyField(to="cartapp.product"),
        ),
    ]
