# Generated by Django 4.2.7 on 2024-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0008_remove_orderitem_product_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="products",
            field=models.ManyToManyField(to="cartapp.product"),
        ),
    ]
