# Generated by Django 4.2.7 on 2024-01-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0009_remove_orderitem_product_orderitem_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cartapp.order"
                    ),
                ),
                ("products", models.ManyToManyField(to="cartapp.product")),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("special", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cartapp.order"
                    ),
                ),
                ("products", models.ManyToManyField(to="cartapp.product")),
            ],
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
