# Generated by Django 4.2.7 on 2024-01-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0010_orderitem1_orderitem2_delete_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem1",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem2",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
