# Generated by Django 4.2.7 on 2024-01-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0011_alter_order_total_price_alter_orderitem1_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem1",
            name="products",
        ),
        migrations.AddField(
            model_name="orderitem1",
            name="products",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cartapp.product",
            ),
        ),
    ]
