# Generated by Django 4.2.7 on 2024-01-18 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0012_remove_orderitem1_products_orderitem1_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="orderitem2",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem2",
            name="products",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="OrderItem1",
        ),
        migrations.DeleteModel(
            name="OrderItem2",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cartapp.order"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="products",
            field=models.ManyToManyField(to="cartapp.product"),
        ),
    ]
