# Generated by Django 4.2.7 on 2024-01-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0013_orderitem_remove_orderitem2_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ref_code",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
